version: 2
jobs:
  build:
    docker:
      - image: docker:18.09-git
    steps:
      - run: |
          apk add --no-cache bash curl
      - checkout
      - setup_remote_docker
      - run: ./tests/runner.sh 
