#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

cat << EOF

  Please choose a command:

     create-readony-user <database> <username> <password>

     create-user-db <username> <password>

     delete-user-db <username>

     fix-owner <databases>

     load <databases>

     psql - start a PostgreSQL client session

     save <databases>

     vacuum <databases>

EOF
