#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

cat << EOF

  Please choose a command:

     create-user-db <username> <password>

     delete-user-db <username>

     dump <databases>

     psql - start a PostgreSQL client session

     restore <databases>

     vacuum <databases>

EOF
