#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

[[ "${DEBUG:-}" == 'true' ]] && set -x

# shellcheck source=commands/common.sh
. "$(dirname "${0}")/common.sh"

parse_options "${@}"

connection_string="${connection[*]}"
echoerr ">>> Connection: ${connection_string//$'\n'/ }"

exec /usr/bin/psql "${connection[@]}"
