#!/usr/bin/env bash

set -e -o pipefail
[ "$DEBUG" == 'true' ] && set -x
. "$(dirname $0)/"common.sh

if [ -z "$DUMP_DIR" ]; then
    echo "DUMP_DIR not set"
    exit 128
fi

wait_postgres

if [ -z "$1" ]; then
    DUMPS=$(find ${DUMP_DIR} -name '*.sql.gz' | xargs -n 1 -I % basename % .sql.gz )
else
    DUMPS=$@
fi

echo -n "Restoring..."
for DB in $DUMPS; do
    echo -n " $DB"
    zcat ${DUMP_DIR}/${DB}.sql.gz | $PSQL --dbname=${DB}
    # Change object ownership to DB user
    (
      $PSQL --dbname=${DB} -t -c "SELECT 'ALTER TABLE '|| schemaname || '.' || tablename ||' OWNER TO ${DB};' FROM pg_tables WHERE NOT schemaname IN ('pg_catalog', 'information_schema') ORDER BY schemaname, tablename;"
      $PSQL --dbname=${DB} -t -c "SELECT 'ALTER SEQUENCE '|| sequence_schema || '.' || sequence_name ||' OWNER TO ${DB};' FROM information_schema.sequences WHERE NOT sequence_schema IN ('pg_catalog', 'information_schema') ORDER BY sequence_schema, sequence_name;"
      $PSQL --dbname=${DB} -t -c "SELECT 'ALTER VIEW '|| table_schema || '.' || table_name ||' OWNER TO ${DB};' FROM information_schema.views WHERE NOT table_schema IN ('pg_catalog', 'information_schema') ORDER BY table_schema, table_name;"
    ) | $PSQL --dbname=${DB}
done
echo ". Done."

echo "Finished."
