#!/usr/bin/env bash

set -e -o pipefail
[ "$DEBUG" == 'true' ] && set -x
. "$(dirname $0)/"common.sh

if [ -z "$DUMP_DIR" ]; then
    echo "DUMP_DIR not set"
    exit 128
fi

wait_postgres

: ${PGDUMP_ARGS:='--no-owner --no-acl --format=plain'}

if [ -z "$1" ]; then
    DATABASES=$($PSQL -t -c "SELECT datname FROM pg_database WHERE datname NOT IN ('template0', 'template1');")
else
    DATABASES=$@
fi

echo -n "Dumping..."
for DB in $DATABASES; do
    echo -n " $DB"
    $PGDUMP ${PGDUMP_ARGS} ${DB} | $GZIP > ${DUMP_DIR}/${DB}.sql.gz
done
echo ". Done."

echo "Finished."
