#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

cat << EOF

  Please choose a command:

     create-user-db

     drop-user-db

     pg-ping

     pganalyze

     psql

     report

     save

     vacuumdb

EOF
