#!/usr/bin/env bash

set -e -o pipefail
[ "$DEBUG" == 'true' ] && set -x
. "$(dirname $0)/"common.sh

wait_postgres

if [ -z "$1" ]; then
    DATABASES=$($PSQL -t -c "SELECT datname FROM pg_database WHERE datname NOT IN ('template0', 'template1');")
else
    DATABASES=$@
fi

# Perform the vacuum
echo -n "Vacuuming..."
for DB in $DATABASES; do
    echo -n " $DB"
    $PSQL -t --dbname=${DB} -c 'VACUUM FULL;' > /dev/null
done
echo ". Done."

echo "Finished."
